### PR TITLE
Clean call register..

### PR DESCRIPTION
**Pull request by luyahan**

### CODE REVIEW

**Review by qjivy — DISMISSED** [review]

**Comment by luyahan** [comment]
/retest-run
//retest-precheck

**Comment by fw-brice** [comment]
> /retest-run
> /retest-precheck

I didn't enable this yet, but it would probably make sense to support that too. Right now, it is only checking to match the entire body. This may be more convenient to match anywhere in the body. I'll open an issue to make that change sometime.

**Comment by luyahan** [comment]
'proposals/js-types/exports':
don't failed now.

**Review by qjivy — APPROVED** [review]

**Pull request merged**
